{% set name = "parsl" %}
{% set version = "0.8.0" %}
{% set sha256 = "336f665a2cec879850d2e4328de9e91e1e881da13b62858003079a0d928829be" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Parsl/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - parsl-globus-auth = parsl.data_provider.globus:cli_run

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pyzmq>=17.1.2
    - typeguard
    - ipyparallel
    - globus-sdk
    - dill
    - tblib
    - ipykernel
    - requests
    - paramiko
    - psutil
    - sqlalchemy==1.3.3
    - sqlalchemy_utils
    - pydot
    - networkx
    - Flask
    - flask_sqlalchemy
    - pandas
    - plotly
    - python-daemon

test:
  imports:
    - parsl

about:
  home: https://github.com/Parsl/parsl
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Simple parallel workflows system for Python'

  description: |
    Parsl is a Python library for programming and executing 
    data-oriented workflows (dataflows) in parallel.
  doc_url: https://parsl.readthedocs.io/
  dev_url: https://github.com/Parsl/parsl

extra:
  recipe-maintainers:
    - ZhuozhaoLi
    - yadudoc
