{% set name = "parsl" %}
{% set version = "0.9.0" %}
{% set sha256 = "6bd29350fa13e3b5efbd7cd21b37b299eb31fe1501602494b4a2dbdaff0a8cbf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Parsl/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - parsl-globus-auth = parsl.data_provider.globus:cli_run

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pyzmq >=17.1.2
    - typeguard
    - ipyparallel
    - globus-sdk
    - dill
    - tblib
    - ipykernel
    - requests
    - paramiko
    - psutil
    - sqlalchemy ==1.3.3
    - sqlalchemy-utils
    - pydot
    - networkx
    - Flask
    - flask-sqlalchemy
    - pandas
    - plotly
    - python-daemon

test:
  imports:
    - parsl

about:
  home: https://github.com/Parsl/parsl
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Simple parallel workflows system for Python'

  description: |
    Parsl is a Python library for programming and executing 
    data-oriented workflows (dataflows) in parallel.
  doc_url: https://parsl.readthedocs.io/
  dev_url: https://github.com/Parsl/parsl

extra:
  recipe-maintainers:
    - ZhuozhaoLi
    - yadudoc
