{% set name = "parsl" %}
{% set version = "1.1.0" %}
{% set sha256 = "6a623d3550329f028775950d23a2cafcb0f82b199f15940180410604aa5d102c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Parsl/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - parsl-globus-auth = parsl.data_provider.globus:cli_run

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pyzmq >=17.1.2
    - typeguard >=2.5
    - ipyparallel
    - globus-sdk
    - dill
    - tblib
    - ipykernel
    - requests
    - paramiko
    - psutil >=5.5.1
    - sqlalchemy >=1.3.0,!=1.3.4,<1.4
    - sqlalchemy-utils
    - pydot
    - networkx
    - flask >=1.0.2
    - flask-sqlalchemy
    - pandas
    - plotly
    - python-daemon

test:
  requires:
    - pip
  imports:
    - parsl
  commands:
    - pip check

about:
  home: https://github.com/Parsl/parsl
  license: Apache-2.0
  license_file: LICENSE
  summary: Simple parallel workflows system for Python

  description: |
    Parsl is a Python library for programming and executing 
    data-oriented workflows (dataflows) in parallel.
  doc_url: https://parsl.readthedocs.io/
  dev_url: https://github.com/Parsl/parsl

extra:
  recipe-maintainers:
    - ZhuozhaoLi
    - yadudoc
    - xylar
