travis:
  secure:
    BINSTAR_TOKEN: YjTkeSkoeKMzlhLU+mCI9N72pOwhuhyB1H2DI/30NVlC0SQbCt+1ldDw7gRNdntrw+GZw40TfV3eemvDFqLY5ZU/ug++VQ3vytoNMdcBCzoMCDqXX/23FVZxUlB8XJ3ttB5kmYfrmHzSDVbb4s49RoDR0p1zxg1ZeDffXY1Zxtyp1uQbxmetdFfMHlIdlfmUVOVICFwhYxITWY2ZTIAIk4VTd2QrHZJEs2FD8c0zDD+WNeeQAz7QkmeZDyVO/Hi3RVlSNFDSy3RGl80zL0QvWvQPsbTfPrEjq2m938GHP6dXMzXAD+i7kAme/yNNtFo45MmApwNOFf8UDK07BzQATz/+wrEhK5sEqsUtm0GF9Iv09FragQRANVXJQhY57gZ46EO9sOHUJS+EVAZ+jkom7vdLAAYzd58wAUljmsVr41MQv6q11dmoNMLfEBw6uVbjSnNPeuqi3LSaogjQXdhukkdU/VlrwaiRBybJF8yFe6obNy1JmymWjLXYrEAYMNVvXH9E8OjRxEKujwpW9jhygDF/aItpjPn/36USFQNTjhWhbpE6v+0+WWD0R3Omi0lfL86qdctFuoofB9i6JOf2BzM73ItPHnhFDglgr1ro2qHQYZ8KIMkraflY9U3pmp+ogWQAsVpkUKYITIjyg4nscJRhXvCImhzVTCqsgBeTTak=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
